version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.production
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
    image: lodo4ka/devops-for-programmers-project-74
    ports:
      - "8080:8080"
    command: bash -c 'sleep 3 && npm test'

  db:
    volumes:
      - pgdata:/var/lib/postgresql/data
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  caddy:
    depends_on:
      - app
    image: caddy:2.7.6
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - './services/caddy/Caddyfile:/etc/caddy/Caddyfile'

volumes:
  pgdata:
