version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.production
    environment:
      DATABASE_PASSWORD: postgres
      DATABASE_USERNAME: postgres
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    depends_on:
      - db
    image: lodo4ka/devops-for-programmers-project-74
    ports:
      - "8080:8080"
    command: make test

  db:
    volumes:
      - pgdata:/var/lib/postgresql/data
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  caddy:
    depends_on:
      - app
    image: caddy:2.7.6
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - './services/caddy/Caddyfile:/etc/caddy/Caddyfile'

volumes:
  pgdata:
