version: '3'

services:
  app:
    depends_on:
      - db
    image: lodo4ka/devops-for-programmers-project-74
    extends:
      file: docker-compose.override.yml
      service: app
    command: make test
    build:
      context: .
      dockerfile: Dockerfile.production

  db:
    volumes:
      - pgdata:/var/lib/postgresql/data
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  pgdata:
