services:
  app-local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - './app:/app'
    command: 'bash -c \"sleep 3 && npm start\"'

  app-production:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    volumes:
      - './app:/app'
    command: 'bash -c \"sleep 3 && npm start\"'

  caddy:
    depends_on:
      - app-production
    image: caddy:2.7.6
    volumes:
      - './services/caddy/Caddyfile:/etc/caddy/Caddyfile'
    ports:
      - "80:80"
      - "443:443"


