version: '3'

services:
  app:
    depends_on:
      - db
    image: lodo4ka/devops-for-programmers-project-74
    env_file:
      - ./app/.env
    extends:
      file: docker-compose.override.yml
      service: app
    build:
      context: .
      dockerfile: Dockerfile.production

  db:
    volumes:
      - pgdata:/var/lib/postgresql/data
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - main-network

volumes:
  pgdata:
